### PR TITLE
Enable support for rails 7.1

### PR DESCRIPTION
**Pull request by kevinrobayna**
https://rubyonrails.org/2023/10/5/Rails-7-1-0-has-been-released

### CODE REVIEW

**Comment by kevinrobayna** [comment]
I have a feeling the build in master are broken since it's failing to run 6.1

**Comment by igor-alexandrov** [comment]
To add support for Rails 7.2 we probably should drop support for < 6.1.
* pg_party uses very old version of rspec-rails and rspec-mocks, AR 7.1 added `.with` method, which broke old versions of RSpec. Read more here: https://github.com/rspec/rspec-mocks/issues/1530
* Also `database_cleaner` < 2.0 will not work with AR 7.1 and if we will continue to support on AR >= 6.1 than it is not needed at all, because we can use `ActiveRecord::Tasks::DatabaseTasks.truncate_all`.

Let me know what do you think.

**Comment by rkrage** [comment]
Thanks for getting this going. It seems like there's a bit more work to do, so I'm gonna start working in a separate branch (I'll add both of you as coauthors on the commit)

**Comment by igor-alexandrov** [comment]
@rkrage I almost done everything in #78. One test fails with AR 7.1 and I cannot really understand why... Please take a look.

**Comment by igor-alexandrov** [comment]
@rkrage by the way, what do you think about moving from Circle to GitHub Actions?

**Comment by rkrage** [comment]
Alright, I have this PR that combines both of your work with some additional cleanup: https://github.com/rkrage/pg_party/pull/79

**Comment by rkrage** [comment]
> what do you think about moving from Circle to GitHub Actions?

I'm not opposed, but I'm not sure if I have the time to work on that. This project is basically in maintenance mode right now. I don't plan to add any new features

**Comment by igor-alexandrov** [comment]
> > what do you think about moving from Circle to GitHub Actions?
> 
> I'm not opposed, but I'm not sure if I have the time to work on that. This project is basically in maintenance mode right now. I don't plan to add any new features

I will try to do this.

**Comment by rkrage** [comment]
Closing in favor of https://github.com/rkrage/pg_party/pull/79

**Comment by igor-alexandrov** [comment]
@kevinrobayna please close this one in favour of #79

**Pull request closed without merging**
