### PR TITLE
Activerecord 6.1 inclusion in runtime dependency

### PR DESCRIPTION
**Pull request by nukah**

### CODE REVIEW

**Comment by rkrage** [comment]
I actually ran the tests against 6.1 and am seeing several failures. Might take me a bit of time to sort out what's going on

**Comment by arrowcircle** [comment]
Any updates on this?

**Comment by rkrage** [comment]
@arrowcircle I have a branch going: https://github.com/rkrage/pg_party/compare/rails-6.1

Got it down to 13 failures, but it looks like some internal APIs have changed 😢 

https://app.circleci.com/pipelines/github/rkrage/pg_party/42/workflows/efceda56-4470-4f78-93c4-71466457f864/jobs/1533

Hopefully I can get this sorted out soon.

@webandtech would you have some time to help look into this? The failures are around the `add_index_on_all_partitions` method

**Comment by webandtech** [comment]
@rkrage will do this week!

**Comment by rkrage** [comment]
I'm gonna spend a few hours on it this afternoon, but I'll let you know if I get stuck

**Comment by rkrage** [comment]
@webandtech well I think this fixes the tests but it makes me want to throw up a little bit: https://github.com/rkrage/pg_party/commit/44c5aa00cd836c420606210aed4ca1e8371717f2

Lemme know if you have other ideas. I also don't know robust this solution is...

**Comment by rkrage** [comment]
@nukah, @arrowcircle version 1.5.0 was released with Rails 6.1 support

**Pull request closed without merging**
