### PR TITLE
Ignore child partition tables in structure dump

### LINKED ISSUE #36: Schema file contains partion tables
When migrations are run and a new schema.sql file is generated, it contains the user-created partition tables for any partitions in the database. This is expected, but also seems wrong since in a multi-dev environment, there will be constant differences in this file since everyone will have different partitions.

Perhaps there's a way to instruct the schema generator to only dump the master partition record.

### PR DESCRIPTION
**Pull request by rkrage**
Resolves #36 

This change relies on `SchemaDumper.ignore_tables` which was only recently modified to work with a structure dump: https://github.com/rails/rails/pull/29077

@justinperkins it'll be pretty difficult to get this working for Rails <5.2. Is this enough to unblock you?

### CODE REVIEW

**Comment by justinperkins** [comment]
I'm locked on 5.1 for now, so just going to have to continue to do with schema nonsense. It hasn't been a big deal really, just noise in our commits. Thanks for adding this, look forward to getting it one day!

**Comment by rkrage** [comment]
Ah shoot. Let me think on this one. It might not be _too_ difficult to get it working for 5.1

**Comment by justinperkins** [comment]
We're working on the upgrade, it's just been on the back burner. I wouldn't spend time on it if I were you

**Comment by rkrage** [comment]
It was actually pretty simple (and potentially better) than the previous solution: https://github.com/rkrage/pg_party/compare/exclude-partitions. I'll try to get that merged in and tag a new patch release this evening.

**Comment by justinperkins** [comment]
Ha! Simple and potentially better is great!

**Comment by rkrage** [comment]
Released in `1.2.1`

**Pull request merged**
