### PR TITLE
add note about indexes

### PR DESCRIPTION
**Pull request by justinperkins**

### CODE REVIEW

**Comment by rkrage** [comment]
That's a good callout. For this example, maybe it would make sense to explicitly give the child partition table a name to highlight that feature:

```ruby
create_list_partition_of \
  :some_list_records,
  name: :some_list_records_partition,
  partition_key: :id,
  values: (1..100).to_a

add_index :some_list_records_partition, :some_foreign_id
```

Also, maybe the description should read something like:
> If a partitioned table requires an index on a column other than the partition key, an explicit `add_index` operation is required for each child partition

**Comment by rkrage** [comment]
Also, it's worth noting that I currently have a branch in progress for creating partitions from a template table. This will allow a partition to copy the schema, including indexes, from an existing table. Hopefully I can get that merged in the next few days.

https://github.com/rkrage/pg_party/compare/create_partition_like

**Comment by justinperkins** [comment]
Nice, that will be a handy addition. Updating the description to make it abundantly clear that indexes need to be created on partitions seems like a good idea.

**Comment by justinperkins** [comment]
Didn't even realize that supplying a name to the partition was a feature, glad you pointed that out as well (just saw the bug report relating to it)

**Comment by rkrage** [comment]
Thanks for making those changes. Yeah, more comprehensive documentation is certainly on my todo list. Just need to find the time...

**Pull request merged**
