### PR TITLE
WIP: Support rails 7

### PR DESCRIPTION
**Pull request by dixpac**
This is attempt to support Rails 7. Still work in progress :)

Currently all tests are passing locally, but I have an issue when creating the range partiton:

```
PG::FeatureNotSupported: ERROR:  unsupported PRIMARY KEY constraint with partition key definition
DETAIL:  PRIMARY KEY constraints cannot be used when partition keys include expressions.
/Users/dixpac/Documents/park/lols/demoaza/db/migrate/20211216135943_create_some_range_records.rb:4:in `up'
```

### CODE REVIEW

**Comment by grantspeelman** [comment]
anything i can do to help get this over the line?

**Comment by rkrage** [comment]
Apologies, I haven't been doing a great job of maintaining this project lately. I can try to take a look at this next week

**Comment by dixpac** [comment]
TBH, I thought this gem is not maintained anymore so we ditch it and implemented partition from scratch/manually.

But, @rkrage thanks for you work it served us well :)

**Comment by camol** [comment]
@rkrage did you find some time to Rails 7 adjustments?

**Comment by rkrage** [comment]
Alright, I cherry-picked some of these changes to master and just released version `1.6.0`. @dixpac, I know you're no longer using this gem, but if you could open a new issue and provide some context for that error you were seeing, that would be awesome.

Thanks all!

**Pull request closed without merging**
