### PR TITLE
Introduce create_partition_like migration method

### PR DESCRIPTION
**Pull request by rkrage**
This partially addresses #17. Will open another PR to create some model helpers.

### CODE REVIEW

**Comment by rkrage** [comment]
cc @justinperkins 

Sorry this took so long!

**Comment by justinperkins** [comment]
Very nice, this is so that you can create future partitions without being concerned with table schema, right?

**Comment by rkrage** [comment]
Yup. This migration method lets you completely duplicate a table (including indexes, defaults, constraints, etc). So you'll simply be able to clone a child partition and attach it to the parent without additional `add_index` calls. I'm thinking I can modify the model helpers a bit to perform these actions in a single method call. One step closer automatic partition creation.

**Comment by rkrage** [comment]
Keep an eye on the project. I've been working towards a 1.0 release 😄

**Comment by justinperkins** [comment]
In my use case, no partitions are created in the initial migration that creates the partitioned table. So it still requires the `add_index` calls living somewhere outside a migration. Any thoughts on how to get those calls back into migration land where they belong?

I am using a date-based partition, so I *could* create the partition table for the current date, but that also feels a bit hacky.

**Comment by rkrage** [comment]
Agreed that using current date in a migration is pretty hacky. Having deterministic migrations should always be a goal.

That being said, I think you could create the parent table in a migration, as well as a template table with all your indexes, defaults, constraints, etc. You wouldn't actually attach this table as a partition, and the model helpers I'm working on could take some sort of template table option when creating new partitions. Thoughts?

**Comment by rkrage** [comment]
A more concrete example of what I'm thinking: https://github.com/rkrage/pg_party/blob/50ef7da71c5ae00fef5f6e0a4064b7da956f1f45/spec/internal/db/schema.rb#L9-L38

The creating from a template table / attaching would be exposed as a single model method for convenience.

My WIP branch: https://github.com/rkrage/pg_party/compare/table_like_helpers

**Comment by justinperkins** [comment]
I like the idea of a template table. Do you see that being a standard table named with some sort of convention based on the partition table?

**Comment by rkrage** [comment]
Yeah I guess following the "rails way" of convention over configuration, a template table could automatically be created with some suffix after creating the parent partition. Then it could be for creating child partitions going forward

**Comment by rkrage** [comment]
Would love some eyes on https://github.com/rkrage/pg_party/pull/31

Tried to request a review, but I guess you need to be a collaborator on the project for that feature 🤷‍♂️

**Pull request merged**
