### PR TITLE
Query methods for complex keys

### LINKED ISSUE #34: Add support for complex partition key query methods
Since ActiveRecord does some crazy aliasing when joins are involved, I think we'll need to do some subquery magic for `partition_key_eq` and `partition_key_in` to be chainable.

### PR DESCRIPTION
**Pull request by rkrage**
Introduces some subquery shenanigans to resolve #34.

 @justinperkins could you take a look at this? Sorry I haven't been very active on this project recently...

I think we just need to update the docs and cut a new release once this is merged.

### CODE REVIEW

**Comment by justinperkins** [comment]
Whoa nice! Cool to see some activity on here. I've been super heads down myself and chugging along with my pg-party variant, but I know I said I'd do things and I still haven't done. 

I need a bit of time to parse this PR but will followup soon. Thanks for keeping me in the loop

**Comment by rkrage** [comment]
I appreciate it. I'm interested to see what you've been doing and if there's an opportunity to collaborate!

**Comment by rkrage** [comment]
```

**Comment by rkrage** [comment]
For a bit of context, the goal here is generate queries that are chainable in AR. Since partition key expressions (likely) won't use fully qualified column names, I'm trying to isolate logic in a subquery to avoid collisions in column names during a join. An example query:
```
SELECT "bigint_month_ranges".*
FROM "bigint_month_ranges"
WHERE "bigint_month_ranges"."id" IN (
  SELECT "bigint_month_ranges"."id"
  FROM "bigint_month_ranges"
  WHERE (
    (EXTRACT(YEAR FROM created_at), EXTRACT(MONTH FROM created_at)) >= (2019,5) AND 
    (EXTRACT(YEAR FROM created_at), EXTRACT(MONTH FROM created_at)) < (2019,6)
  )
)
```

This might result in some inefficient queries, so let me know if you have other ideas.

**Comment by rkrage** [comment]
Just pushed a commit that _hopefully_ generates a more performant query and also removes the PK requirement. It involves a pretty weird AR / Arel hack that I found here: https://stackoverflow.com/questions/28685149/activerecord-query-with-aliasd-table-names

A new example query:
```
SELECT "bigint_month_ranges".*
FROM (
  SELECT *
  FROM "bigint_month_ranges"
  WHERE (
    (EXTRACT(YEAR FROM created_at), EXTRACT(MONTH FROM created_at)) >= (2019,5) AND 
    (EXTRACT(YEAR FROM created_at), EXTRACT(MONTH FROM created_at)) < (2019,6)
  )
) AS "bigint_month_ranges"
```

**Comment by justinperkins** [comment]
@rkrage Can you supply an example migration that creates a table with one of these complex partition keys, or is that unchanged? I've currently got one monster partition running by date (broken into months), and then another partitioning on a primary foreign key (isolating customer data), which is also a beast of data. The latter would be better to be partitioned by the foreign key as well as date (months), but we're on PG 10 and I didn't want to go down that rabbit hole.

**Comment by rkrage** [comment]
That functionality was introduced in https://github.com/rkrage/pg_party/pull/28

Basically a complex partition key is anything other than a column name, e.g. `created_at::date`

In a migration, you simply supply the partition key as a proc: https://github.com/rkrage/pg_party/blob/e2ec669cb12f66c0c0ba20440030dbba453ebcef/spec/internal/db/schema.rb#L9-L11

**Comment by justinperkins** [comment]
I think I'm tracking now. This is strictly speaking in the context of creating new partitions on the fly a more complex key. I have been achieving this by managing the creation of partitions manually and building partition names on the fly based on incoming data.

**Comment by rkrage** [comment]
In your model, you'd supply a complex partition key in a similar fashion (this time as a block):

https://github.com/rkrage/pg_party/blob/e2ec669cb12f66c0c0ba20440030dbba453ebcef/spec/internal/app/models/bigint_date_range.rb#L3-L5

By doing that, all of the range partition model goodies are injected. The more interesting methods are here: https://github.com/rkrage/pg_party/blob/e2ec669cb12f66c0c0ba20440030dbba453ebcef/lib/pg_party/model/shared_methods.rb#L24-L26

And here: https://github.com/rkrage/pg_party/blob/e2ec669cb12f66c0c0ba20440030dbba453ebcef/lib/pg_party/model/range_methods.rb#L8-L14

For your specific use case, I imagine you're dynamically calling `create_partition`. You can see an example of that being called in the tests: https://github.com/rkrage/pg_party/blob/e2ec669cb12f66c0c0ba20440030dbba453ebcef/spec/integration/model/bigint_date_range_spec.rb#L41-L47

And remember, the partition key itself isn't required anymore when creating child partitions. Instead, a copy of the template table is created and then attached. That was introduced in https://github.com/rkrage/pg_party/pull/31.

**Comment by justinperkins** [comment]
Thanks. Yes, I am manually invoking `create_partition` since I have a very old version of `pg_party`. The test you have that uses a substring of a column is a great example of how much more powerful this is now than just IDs and ranges. Next up: compound partition keys (list + range)

**Comment by rkrage** [comment]
I'll start working on a branch for the documentation changes soon!

**Pull request merged**
